[package]
name = "orthanc_client"
version = "0.0.1"
authors = ["Andrii Yurchuk <ay@mntw.re>"]
edition = "2018"
autotests = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.10", features = ["blocking", "json"] }
bytes = "0.5"
chrono = "0.4"

[dev-dependencies]
httpmock = "0.4"
maplit = "1.0"

[[test]]
name = "integration"
path = "tests/test.rs"
