name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    name: unit_test
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: prepare rust env
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: run tests
        run: |
          cargo install cargo-tarpaulin && \
          cargo tarpaulin --verbose --ignore-tests --all-features --workspace --timeout 120 --out Xml

      - name: upload coverage
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

  integration_test:
    runs-on: ubuntu-latest
    name: unit_test
    container:
      image: jodogne/orthanc:latest
      ports:
        - 8042

    env:
      ORC_ORTHANC_ADDRESS: http://localhost:8042

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: prepare rust env
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: run tests
        run: integration_test.sh
