name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: prepare rust env
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: run tests
        run: cargo install cargo-tarpaulin && cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml

      - name: upload coverag
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
